services:
  - type: web
    name: ai-scam-hub-frontend
    runtime: static
    plan: free
    branch: main
    buildCommand: npm install && chmod +x node_modules/.bin/react-scripts && npm run build
    staticPublishPath: ./build